[package]
name = "linear_algebra_ml"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.0"

[profile.release]
lto = true
opt-level = 3

[[bench]]
name = "dense_bench"
harness = false
